# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: push

permissions:
  contents: read

env:
      EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
      EMAIL_USER_NAME : ${{ vars.SENDER_USER_NAME }}

jobs:
  build_and_send:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Debug
      run: |
        echo "EMAIL_PASSWORD: $EMAIL_PASSWORD"
        echo "EMAIL_USER_NAME: $EMAIL_USER_NAME"
    - name: Print All Environment Variables
      run: printenv

    - name: Echo Specific Variables
      run: |
        echo "User Name: $SENDER_USER_NAME"
        echo "Password Length: ${#SENDER_EMAIL_PASSWORD}" #length of password.

    - name: python debug
      run: |
        python -c 'import os; print("python User Name:", os.environ.get("SENDER_USER_NAME")); print("python Password:", os.environ.get("SENDER_EMAIL_PASSWORD"))'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        python send_email.py